---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: auto
  vars:
    project_name: netops
    django_port: 8000
    prometheus_url: "http://localhost:9090"
    grafana_url: "http://localhost:3000"
