---
django_app_dir: "{{ playbook_dir }}/../../django_app"
django_port: 8000
django_secret_key: "{{ vault_django_secret_key }}"
django_debug: false
django_allowed_hosts: "localhost,127.0.0.1"
monitored_services:
  - name: "Google"
    url: "https://google.com"
    check_interval: 60
  - name: "GitHub"
    url: "https://github.com"
    check_interval: 60
  - name: "Python.org"
    url: "https://python.org"
    check_interval: 120
django_superuser_username: "{{ vault_django_superuser_username }}"
django_superuser_email: "{{ vault_django_superuser_email }}"
django_superuser_password: "{{ vault_django_superuser_password }}"
